### PR TITLE
Creation of submission folder

### PR DESCRIPTION
**Pull request by KM-DataAnalyst**
Creation of the basic submission folders, Jupyter Notebook and Markdown files for project

### CODE REVIEW

**Review by Shaheerairaj — CHANGES_REQUESTED** [review]
Hi Karl, instead of uploading a README with your information, could you include this in your notebook that you will submit please?

**Comment by KM-DataAnalyst** [comment]
Hi

The README was just for example purposes to see how the push and pull
requests were handled. I will upload the correct Jupyter notebook as
provided in the example folder.

Thanks for notifying me about this.

Karl Munroe
Mobile/Whatsapp: 876-365-4340

**Comment by MexicanoAfortunado** [comment]
1. Can't pull the submit request
I don't have the git CLI installed, so cannot follow your instructions (yet!).
Also, the GitHub instructions on submitting and pulling requests are foobar'd -- there is no yellow banner to click on at step 3.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

2. Can't make a directory under MM0001-Operation-Mind-Shield/submissions .  There is no option to create a folder.  I can only navigate (e.g. go up the tree or go into the data directory) or create a file.  I did try to create a file, but the only option was to copy and paste the text (Jupyter code), which I did.  However, no new file was created under /submissions, even though I specified the filename michal-karpinski.  The only thing I see is "[MexicanoAfortunado:patch-1] had recent pushes".

Anyway, this is a first attempt since #1 and #2 aren't working.
Cheers.

**Comment by MexicanoAfortunado** [comment]
One more thing -- I did create my own fork yesterday (MexicanoAfortunado), but when I navigate to it, there aren't any options to do anything.  See attached.
fork

Once I install the git CLI, I'll try to follow the CONTRIBUTE.MD doc and if I have time I'll watch the YouTube https://www.youtube.com/watch?v=RGOj5yH7evk

Regards,
MK

**Comment by Shaheerairaj** [comment]
@MexicanoAfortunado 

1. You don't need the GitHub CLI to follow the instructions mentioned in the contributing file. The commands listed are bash command which you can execute in your terminal. If you are using Linux or Mac, these commands should work immediately. If you are using Windows, you might need to install git before you can execute the commands mentioned.

Also, not sure which step 3 you are referring to. Could you clarify this please?

2. Creating your folder in submissions and then the jupyter notebook is to be done on your local machine. Once you have forked your repo and then cloned it to your local machine, the repo should appear as a folder like any other. You can then navigate to the submissions folder and create a new folder with your name.

I would recommend not to use GitHub itself for working on your files as it can be confusing at times and may lead to your GitHub and local environment being out of sync which can lead to issues down the line.

If you need any additional help, feel free to open a discussion about this topic or we can even set a meeting to go through it.

@KM-DataAnalyst I'll be closing the PR and wait for your updates.

**Pull request closed without merging**
